// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: greet.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GreetServiseClient is the client API for GreetServise service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GreetServiseClient interface {
	Greet(ctx context.Context, in *GreetRequest, opts ...grpc.CallOption) (*GreetResponse, error)
}

type greetServiseClient struct {
	cc grpc.ClientConnInterface
}

func NewGreetServiseClient(cc grpc.ClientConnInterface) GreetServiseClient {
	return &greetServiseClient{cc}
}

func (c *greetServiseClient) Greet(ctx context.Context, in *GreetRequest, opts ...grpc.CallOption) (*GreetResponse, error) {
	out := new(GreetResponse)
	err := c.cc.Invoke(ctx, "/greet.GreetServise/Greet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreetServiseServer is the server API for GreetServise service.
// All implementations must embed UnimplementedGreetServiseServer
// for forward compatibility
type GreetServiseServer interface {
	Greet(context.Context, *GreetRequest) (*GreetResponse, error)
	mustEmbedUnimplementedGreetServiseServer()
}

// UnimplementedGreetServiseServer must be embedded to have forward compatible implementations.
type UnimplementedGreetServiseServer struct {
}

func (UnimplementedGreetServiseServer) Greet(context.Context, *GreetRequest) (*GreetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Greet not implemented")
}
func (UnimplementedGreetServiseServer) mustEmbedUnimplementedGreetServiseServer() {}

// UnsafeGreetServiseServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GreetServiseServer will
// result in compilation errors.
type UnsafeGreetServiseServer interface {
	mustEmbedUnimplementedGreetServiseServer()
}

func RegisterGreetServiseServer(s grpc.ServiceRegistrar, srv GreetServiseServer) {
	s.RegisterService(&GreetServise_ServiceDesc, srv)
}

func _GreetServise_Greet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GreetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreetServiseServer).Greet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greet.GreetServise/Greet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreetServiseServer).Greet(ctx, req.(*GreetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GreetServise_ServiceDesc is the grpc.ServiceDesc for GreetServise service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GreetServise_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "greet.GreetServise",
	HandlerType: (*GreetServiseServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Greet",
			Handler:    _GreetServise_Greet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "greet.proto",
}
